// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  expenseId: __t.u64().primaryKey().name("expense_id"),
  flatId: __t.u64().name("flat_id"),
  expenseDate: __t.timestamp().name("expense_date"),
  recordedAt: __t.timestamp().name("recorded_at"),
  splitMethod: __t.string().name("split_method"),
  recordedBy: __t.identity().name("recorded_by"),
});
