// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  flatId: __t.u64().name("flat_id"),
  debtorIdentity: __t.identity().name("debtor_identity"),
  creditorIdentity: __t.identity().name("creditor_identity"),
  amountPaise: __t.i64().name("amount_paise"),
  settledBy: __t.identity().name("settled_by"),
  settledAt: __t.timestamp().name("settled_at"),
  method: __t.string(),
});
