// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.0 (commit baca5cdf77577ed4e3f30da48a5158189c4ea43f).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AddPantryItemReducer from "./add_pantry_item_reducer";
import AppendConversationMessageReducer from "./append_conversation_message_reducer";
import AppendConversationMessageOnceReducer from "./append_conversation_message_once_reducer";
import ClearAllDataReducer from "./clear_all_data_reducer";
import ConfirmShoppingOrderToPantryReducer from "./confirm_shopping_order_to_pantry_reducer";
import CreateAndJoinFlatReducer from "./create_and_join_flat_reducer";
import CreateConversationReducer from "./create_conversation_reducer";
import CreateHomeAndJoinReducer from "./create_home_and_join_reducer";
import CreateResidenceReducer from "./create_residence_reducer";
import DeleteFlatRuleReducer from "./delete_flat_rule_reducer";
import DeleteShoppingAgentStateReducer from "./delete_shopping_agent_state_reducer";
import JoinFlatReducer from "./join_flat_reducer";
import RecordExpenseReducer from "./record_expense_reducer";
import RecordExpenseV2Reducer from "./record_expense_v_2_reducer";
import SetAiConfigReducer from "./set_ai_config_reducer";
import SetDisplayNameReducer from "./set_display_name_reducer";
import SettleExpensePairReducer from "./settle_expense_pair_reducer";
import UpdateResidenceFlatReducer from "./update_residence_flat_reducer";
import UpsertFlatRuleReducer from "./upsert_flat_rule_reducer";
import UpsertSharedMemoryReducer from "./upsert_shared_memory_reducer";
import UpsertShoppingAgentStateReducer from "./upsert_shopping_agent_state_reducer";

// Import all procedure arg schemas
import * as RunAiProcedure from "./run_ai_procedure";

// Import all table schema definitions
import ExpenseRow from "./expense_table";
import ExpenseMetadataRow from "./expense_metadata_table";
import ExpenseSettlementRow from "./expense_settlement_table";
import ExpenseSplitRow from "./expense_split_table";
import FlatRow from "./flat_table";
import FlatRuleRow from "./flat_rule_table";
import MemberRow from "./member_table";
import MyAiStatusRow from "./my_ai_status_table";
import MyConversationMessagesRow from "./my_conversation_messages_table";
import MyConversationsRow from "./my_conversations_table";
import MyShoppingAgentStatesRow from "./my_shopping_agent_states_table";
import PantryItemRow from "./pantry_item_table";
import ResidenceRow from "./residence_table";
import SharedMemoryRow from "./shared_memory_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  expense: __table({
    name: 'expense',
    indexes: [
      { accessor: 'flat_id', name: 'expense_flat_id_idx_btree', algorithm: 'btree', columns: [
        'flatId',
      ] },
      { accessor: 'id', name: 'expense_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'expense_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ExpenseRow),
  expenseMetadata: __table({
    name: 'expense_metadata',
    indexes: [
      { accessor: 'expense_id', name: 'expense_metadata_expense_id_idx_btree', algorithm: 'btree', columns: [
        'expenseId',
      ] },
      { accessor: 'flat_id', name: 'expense_metadata_flat_id_idx_btree', algorithm: 'btree', columns: [
        'flatId',
      ] },
    ],
    constraints: [
      { name: 'expense_metadata_expense_id_key', constraint: 'unique', columns: ['expenseId'] },
    ],
  }, ExpenseMetadataRow),
  expenseSettlement: __table({
    name: 'expense_settlement',
    indexes: [
      { accessor: 'creditor_identity', name: 'expense_settlement_creditor_identity_idx_btree', algorithm: 'btree', columns: [
        'creditorIdentity',
      ] },
      { accessor: 'debtor_identity', name: 'expense_settlement_debtor_identity_idx_btree', algorithm: 'btree', columns: [
        'debtorIdentity',
      ] },
      { accessor: 'flat_id', name: 'expense_settlement_flat_id_idx_btree', algorithm: 'btree', columns: [
        'flatId',
      ] },
      { accessor: 'id', name: 'expense_settlement_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'expense_settlement_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ExpenseSettlementRow),
  expenseSplit: __table({
    name: 'expense_split',
    indexes: [
      { accessor: 'expense_id', name: 'expense_split_expense_id_idx_btree', algorithm: 'btree', columns: [
        'expenseId',
      ] },
      { accessor: 'id', name: 'expense_split_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'member_identity', name: 'expense_split_member_identity_idx_btree', algorithm: 'btree', columns: [
        'memberIdentity',
      ] },
    ],
    constraints: [
      { name: 'expense_split_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ExpenseSplitRow),
  flat: __table({
    name: 'flat',
    indexes: [
      { accessor: 'id', name: 'flat_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'residence_id', name: 'flat_residence_id_idx_btree', algorithm: 'btree', columns: [
        'residenceId',
      ] },
    ],
    constraints: [
      { name: 'flat_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, FlatRow),
  flatRule: __table({
    name: 'flat_rule',
    indexes: [
      { accessor: 'flat_id', name: 'flat_rule_flat_id_idx_btree', algorithm: 'btree', columns: [
        'flatId',
      ] },
      { accessor: 'id', name: 'flat_rule_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'rule_type', name: 'flat_rule_rule_type_idx_btree', algorithm: 'btree', columns: [
        'ruleType',
      ] },
    ],
    constraints: [
      { name: 'flat_rule_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, FlatRuleRow),
  member: __table({
    name: 'member',
    indexes: [
      { accessor: 'flat_id', name: 'member_flat_id_idx_btree', algorithm: 'btree', columns: [
        'flatId',
      ] },
      { accessor: 'identity', name: 'member_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'member_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, MemberRow),
  pantryItem: __table({
    name: 'pantry_item',
    indexes: [
      { accessor: 'flat_id', name: 'pantry_item_flat_id_idx_btree', algorithm: 'btree', columns: [
        'flatId',
      ] },
      { accessor: 'id', name: 'pantry_item_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'name', name: 'pantry_item_name_idx_btree', algorithm: 'btree', columns: [
        'name',
      ] },
    ],
    constraints: [
      { name: 'pantry_item_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PantryItemRow),
  residence: __table({
    name: 'residence',
    indexes: [
      { accessor: 'id', name: 'residence_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'residence_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ResidenceRow),
  sharedMemory: __table({
    name: 'shared_memory',
    indexes: [
      { accessor: 'category', name: 'shared_memory_category_idx_btree', algorithm: 'btree', columns: [
        'category',
      ] },
      { accessor: 'flat_id', name: 'shared_memory_flat_id_idx_btree', algorithm: 'btree', columns: [
        'flatId',
      ] },
      { accessor: 'id', name: 'shared_memory_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'subject_identity', name: 'shared_memory_subject_identity_idx_btree', algorithm: 'btree', columns: [
        'subjectIdentity',
      ] },
    ],
    constraints: [
      { name: 'shared_memory_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SharedMemoryRow),
  myAiStatus: __table({
    name: 'my_ai_status',
    indexes: [
    ],
    constraints: [
    ],
  }, MyAiStatusRow),
  myConversationMessages: __table({
    name: 'my_conversation_messages',
    indexes: [
    ],
    constraints: [
    ],
  }, MyConversationMessagesRow),
  myConversations: __table({
    name: 'my_conversations',
    indexes: [
    ],
    constraints: [
    ],
  }, MyConversationsRow),
  myShoppingAgentStates: __table({
    name: 'my_shopping_agent_states',
    indexes: [
    ],
    constraints: [
    ],
  }, MyShoppingAgentStatesRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("add_pantry_item", AddPantryItemReducer),
  __reducerSchema("append_conversation_message", AppendConversationMessageReducer),
  __reducerSchema("append_conversation_message_once", AppendConversationMessageOnceReducer),
  __reducerSchema("clear_all_data", ClearAllDataReducer),
  __reducerSchema("confirm_shopping_order_to_pantry", ConfirmShoppingOrderToPantryReducer),
  __reducerSchema("create_and_join_flat", CreateAndJoinFlatReducer),
  __reducerSchema("create_conversation", CreateConversationReducer),
  __reducerSchema("create_home_and_join", CreateHomeAndJoinReducer),
  __reducerSchema("create_residence", CreateResidenceReducer),
  __reducerSchema("delete_flat_rule", DeleteFlatRuleReducer),
  __reducerSchema("delete_shopping_agent_state", DeleteShoppingAgentStateReducer),
  __reducerSchema("join_flat", JoinFlatReducer),
  __reducerSchema("record_expense", RecordExpenseReducer),
  __reducerSchema("record_expense_v_2", RecordExpenseV2Reducer),
  __reducerSchema("set_ai_config", SetAiConfigReducer),
  __reducerSchema("set_display_name", SetDisplayNameReducer),
  __reducerSchema("settle_expense_pair", SettleExpensePairReducer),
  __reducerSchema("update_residence_flat", UpdateResidenceFlatReducer),
  __reducerSchema("upsert_flat_rule", UpsertFlatRuleReducer),
  __reducerSchema("upsert_shared_memory", UpsertSharedMemoryReducer),
  __reducerSchema("upsert_shopping_agent_state", UpsertShoppingAgentStateReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
  __procedureSchema("run_ai", RunAiProcedure.params, RunAiProcedure.returnType),
);

type __SchemaWithTableAccessorAliases = Omit<typeof tablesSchema.schemaType, "tables"> & {
  tables: typeof tablesSchema.schemaType.tables & {
    /** @deprecated Use `myAiStatus` instead. This alias will be removed in the next major version. */
    readonly "my_ai_status": Omit<typeof tablesSchema.schemaType.tables["myAiStatus"], "accessorName"> & { readonly accessorName: "my_ai_status" };
    /** @deprecated Use `myConversationMessages` instead. This alias will be removed in the next major version. */
    readonly "my_conversation_messages": Omit<typeof tablesSchema.schemaType.tables["myConversationMessages"], "accessorName"> & { readonly accessorName: "my_conversation_messages" };
    /** @deprecated Use `myConversations` instead. This alias will be removed in the next major version. */
    readonly "my_conversations": Omit<typeof tablesSchema.schemaType.tables["myConversations"], "accessorName"> & { readonly accessorName: "my_conversations" };
    /** @deprecated Use `myShoppingAgentStates` instead. This alias will be removed in the next major version. */
    readonly "my_shopping_agent_states": Omit<typeof tablesSchema.schemaType.tables["myShoppingAgentStates"], "accessorName"> & { readonly accessorName: "my_shopping_agent_states" };
  };
};

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.10.0" as const,
  },
  tables: tablesSchema.schemaType.tables as __SchemaWithTableAccessorAliases["tables"],
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  __SchemaWithTableAccessorAliases,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

const tableAccessorAliases = {
  "my_ai_status": "myAiStatus",
  "my_conversation_messages": "myConversationMessages",
  "my_conversations": "myConversations",
  "my_shopping_agent_states": "myShoppingAgentStates",
} as const;

function __withTableAccessorAliases<T extends object>(target: T, freeze = false): T {
  const out = Object.create(Object.getPrototypeOf(target)) as T & Record<string, unknown>;
  Object.defineProperties(out, Object.getOwnPropertyDescriptors(target));
  for (const [deprecatedAccessor, targetAccessor] of Object.entries(tableAccessorAliases)) {
    if (deprecatedAccessor in out) {
      continue;
    }
    Object.defineProperty(out, deprecatedAccessor, {
      enumerable: true,
      configurable: false,
      get: () => out[targetAccessor],
    });
  }
  return freeze ? Object.freeze(out) : out;
}
type __DbViewBase = __DbConnectionImpl<typeof REMOTE_MODULE>["db"];
export type DbView = __DbViewBase & {
  /** @deprecated Use `myAiStatus` instead. This alias will be removed in the next major version. */
  readonly "my_ai_status": __DbViewBase["myAiStatus"];
  /** @deprecated Use `myConversationMessages` instead. This alias will be removed in the next major version. */
  readonly "my_conversation_messages": __DbViewBase["myConversationMessages"];
  /** @deprecated Use `myConversations` instead. This alias will be removed in the next major version. */
  readonly "my_conversations": __DbViewBase["myConversations"];
  /** @deprecated Use `myShoppingAgentStates` instead. This alias will be removed in the next major version. */
  readonly "my_shopping_agent_states": __DbViewBase["myShoppingAgentStates"];
};

type __TablesBase = __QueryBuilder<typeof tablesSchema.schemaType>;
export type Tables = __TablesBase & {
  /** @deprecated Use `myAiStatus` instead. This alias will be removed in the next major version. */
  readonly "my_ai_status": __TablesBase["myAiStatus"];
  /** @deprecated Use `myConversationMessages` instead. This alias will be removed in the next major version. */
  readonly "my_conversation_messages": __TablesBase["myConversationMessages"];
  /** @deprecated Use `myConversations` instead. This alias will be removed in the next major version. */
  readonly "my_conversations": __TablesBase["myConversations"];
  /** @deprecated Use `myShoppingAgentStates` instead. This alias will be removed in the next major version. */
  readonly "my_shopping_agent_states": __TablesBase["myShoppingAgentStates"];
};

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
const tablesBase: __TablesBase = __makeQueryBuilder(tablesSchema.schemaType);
export const tables: Tables = __withTableAccessorAliases(tablesBase, true) as Tables;

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = Omit<__EventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = Omit<__ReducerEventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = Omit<__SubscriptionEventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for error events. */
export type ErrorContext = Omit<__ErrorContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  declare db: DbView;

  constructor(config: __DbConnectionConfig<typeof REMOTE_MODULE>) {
    super(config);
    this.db = __withTableAccessorAliases(this.db) as DbView;
  }

  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}
