// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AddChatMessageReducer from "./add_chat_message_reducer";
import AddPantryItemReducer from "./add_pantry_item_reducer";
import AppendConversationMessageReducer from "./append_conversation_message_reducer";
import ClearAllDataReducer from "./clear_all_data_reducer";
import CreateAndJoinFlatReducer from "./create_and_join_flat_reducer";
import CreateConversationReducer from "./create_conversation_reducer";
import CreateResidenceReducer from "./create_residence_reducer";
import DeleteFlatRuleReducer from "./delete_flat_rule_reducer";
import JoinFlatReducer from "./join_flat_reducer";
import RecordExpenseReducer from "./record_expense_reducer";
import SetAiConfigReducer from "./set_ai_config_reducer";
import SetDisplayNameReducer from "./set_display_name_reducer";
import UpdateResidenceFlatReducer from "./update_residence_flat_reducer";
import UpsertFlatRuleReducer from "./upsert_flat_rule_reducer";
import UpsertSharedMemoryReducer from "./upsert_shared_memory_reducer";

// Import all procedure arg schemas
import * as RunAiProcedure from "./run_ai_procedure";

// Import all table schema definitions
import ChatMessageRow from "./chat_message_table";
import ExpenseRow from "./expense_table";
import ExpenseSplitRow from "./expense_split_table";
import FlatRow from "./flat_table";
import FlatRuleRow from "./flat_rule_table";
import MemberRow from "./member_table";
import MyAiStatusRow from "./my_ai_status_table";
import MyConversationMessagesRow from "./my_conversation_messages_table";
import MyConversationsRow from "./my_conversations_table";
import PantryItemRow from "./pantry_item_table";
import ResidenceRow from "./residence_table";
import SharedMemoryRow from "./shared_memory_table";

/** The schema information for all tables in this module. */
const tablesSchema = __schema({
  residence: __table({
    name: 'residence',
    indexes: [
      { accessor: 'id', name: 'residence_id_idx_btree', algorithm: 'btree', columns: ['id'] },
    ],
    constraints: [
      { name: 'residence_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ResidenceRow),
  flat: __table({
    name: 'flat',
    indexes: [
      { accessor: 'id', name: 'flat_id_idx_btree', algorithm: 'btree', columns: ['id'] },
      { accessor: 'residence_id', name: 'flat_residence_id_idx_btree', algorithm: 'btree', columns: ['residenceId'] },
    ],
    constraints: [
      { name: 'flat_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, FlatRow),
  flatRule: __table({
    name: 'flat_rule',
    indexes: [
      { accessor: 'id', name: 'flat_rule_id_idx_btree', algorithm: 'btree', columns: ['id'] },
      { accessor: 'flat_id', name: 'flat_rule_flat_id_idx_btree', algorithm: 'btree', columns: ['flatId'] },
    ],
    constraints: [
      { name: 'flat_rule_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, FlatRuleRow),
  chatMessage: __table({
    name: 'chat_message',
    indexes: [
      { accessor: 'id', name: 'chat_message_id_idx_btree', algorithm: 'btree', columns: ['id'] },
    ],
    constraints: [
      { name: 'chat_message_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ChatMessageRow),
  expense: __table({
    name: 'expense',
    indexes: [
      { accessor: 'id', name: 'expense_id_idx_btree', algorithm: 'btree', columns: ['id'] },
      { accessor: 'flat_id', name: 'expense_flat_id_idx_btree', algorithm: 'btree', columns: ['flatId'] },
    ],
    constraints: [
      { name: 'expense_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ExpenseRow),
  expenseSplit: __table({
    name: 'expense_split',
    indexes: [
      { accessor: 'expense_id', name: 'expense_split_expense_id_idx_btree', algorithm: 'btree', columns: ['expenseId'] },
      { accessor: 'id', name: 'expense_split_id_idx_btree', algorithm: 'btree', columns: ['id'] },
      { accessor: 'member_identity', name: 'expense_split_member_identity_idx_btree', algorithm: 'btree', columns: ['memberIdentity'] },
    ],
    constraints: [
      { name: 'expense_split_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ExpenseSplitRow),
  member: __table({
    name: 'member',
    indexes: [
      { accessor: 'identity', name: 'member_identity_idx_btree', algorithm: 'btree', columns: ['identity'] },
      { accessor: 'flat_id', name: 'member_flat_id_idx_btree', algorithm: 'btree', columns: ['flatId'] },
    ],
    constraints: [
      { name: 'member_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, MemberRow),
  pantryItem: __table({
    name: 'pantry_item',
    indexes: [
      { accessor: 'id', name: 'pantry_item_id_idx_btree', algorithm: 'btree', columns: ['id'] },
      { accessor: 'flat_id', name: 'pantry_item_flat_id_idx_btree', algorithm: 'btree', columns: ['flatId'] },
      { accessor: 'name', name: 'pantry_item_name_idx_btree', algorithm: 'btree', columns: ['name'] },
    ],
    constraints: [
      { name: 'pantry_item_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PantryItemRow),
  sharedMemory: __table({
    name: 'shared_memory',
    indexes: [
      { accessor: 'category', name: 'shared_memory_category_idx_btree', algorithm: 'btree', columns: ['category'] },
      { accessor: 'id', name: 'shared_memory_id_idx_btree', algorithm: 'btree', columns: ['id'] },
      { accessor: 'flat_id', name: 'shared_memory_flat_id_idx_btree', algorithm: 'btree', columns: ['flatId'] },
      { accessor: 'subject_identity', name: 'shared_memory_subject_identity_idx_btree', algorithm: 'btree', columns: ['subjectIdentity'] },
    ],
    constraints: [
      { name: 'shared_memory_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SharedMemoryRow),
  myAiStatus: __table({
    name: 'my_ai_status',
    indexes: [],
    constraints: [],
  }, MyAiStatusRow),
  myConversationMessages: __table({
    name: 'my_conversation_messages',
    indexes: [],
    constraints: [],
  }, MyConversationMessagesRow),
  myConversations: __table({
    name: 'my_conversations',
    indexes: [],
    constraints: [],
  }, MyConversationsRow),
});

/** The schema information for all reducers in this module. */
const reducersSchema = __reducers(
  __reducerSchema("add_chat_message", AddChatMessageReducer),
  __reducerSchema("add_pantry_item", AddPantryItemReducer),
  __reducerSchema("append_conversation_message", AppendConversationMessageReducer),
  __reducerSchema("clear_all_data", ClearAllDataReducer),
  __reducerSchema("create_and_join_flat", CreateAndJoinFlatReducer),
  __reducerSchema("create_conversation", CreateConversationReducer),
  __reducerSchema("create_residence", CreateResidenceReducer),
  __reducerSchema("delete_flat_rule", DeleteFlatRuleReducer),
  __reducerSchema("join_flat", JoinFlatReducer),
  __reducerSchema("record_expense", RecordExpenseReducer),
  __reducerSchema("set_ai_config", SetAiConfigReducer),
  __reducerSchema("set_display_name", SetDisplayNameReducer),
  __reducerSchema("update_residence_flat", UpdateResidenceFlatReducer),
  __reducerSchema("upsert_flat_rule", UpsertFlatRuleReducer),
  __reducerSchema("upsert_shared_memory", UpsertSharedMemoryReducer),
);

/** The schema information for all procedures in this module. */
const proceduresSchema = __procedures(
  __procedureSchema("run_ai", RunAiProcedure.params, RunAiProcedure.returnType),
);

type __SchemaWithTableAccessorAliases = Omit<typeof tablesSchema.schemaType, "tables"> & {
  tables: typeof tablesSchema.schemaType.tables & {
    /** @deprecated Use `myAiStatus` instead. */
    readonly "my_ai_status": Omit<typeof tablesSchema.schemaType.tables["myAiStatus"], "accessorName"> & { readonly accessorName: "my_ai_status" };
    /** @deprecated Use `myConversationMessages` instead. */
    readonly "my_conversation_messages": Omit<typeof tablesSchema.schemaType.tables["myConversationMessages"], "accessorName"> & { readonly accessorName: "my_conversation_messages" };
    /** @deprecated Use `myConversations` instead. */
    readonly "my_conversations": Omit<typeof tablesSchema.schemaType.tables["myConversations"], "accessorName"> & { readonly accessorName: "my_conversations" };
    readonly "flat_rule": Omit<typeof tablesSchema.schemaType.tables["flatRule"], "accessorName"> & { readonly accessorName: "flat_rule" };
    readonly "pantry_item": Omit<typeof tablesSchema.schemaType.tables["pantryItem"], "accessorName"> & { readonly accessorName: "pantry_item" };
    readonly "shared_memory": Omit<typeof tablesSchema.schemaType.tables["sharedMemory"], "accessorName"> & { readonly accessorName: "shared_memory" };
    readonly "expense_split": Omit<typeof tablesSchema.schemaType.tables["expenseSplit"], "accessorName"> & { readonly accessorName: "expense_split" };
  };
};

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.10.0" as const,
  },
  tables: tablesSchema.schemaType.tables as __SchemaWithTableAccessorAliases["tables"],
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  __SchemaWithTableAccessorAliases,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

const tableAccessorAliases = {
  "my_ai_status": "myAiStatus",
  "my_conversation_messages": "myConversationMessages",
  "my_conversations": "myConversations",
  "flat_rule": "flatRule",
  "pantry_item": "pantryItem",
  "shared_memory": "sharedMemory",
  "expense_split": "expenseSplit",
} as const;

function __withTableAccessorAliases<T extends object>(target: T, freeze = false): T {
  const out = Object.create(Object.getPrototypeOf(target)) as T & Record<string, unknown>;
  Object.defineProperties(out, Object.getOwnPropertyDescriptors(target));
  for (const [deprecatedAccessor, targetAccessor] of Object.entries(tableAccessorAliases)) {
    if (deprecatedAccessor in out) {
      continue;
    }
    Object.defineProperty(out, deprecatedAccessor, {
      enumerable: true,
      configurable: false,
      get: () => out[targetAccessor as keyof typeof out],
    });
  }
  return freeze ? Object.freeze(out) : out;
}

type __DbViewBase = __DbConnectionImpl<typeof REMOTE_MODULE>["db"];
export type DbView = __DbViewBase & {
  readonly "my_ai_status": __DbViewBase["myAiStatus"];
  readonly "my_conversation_messages": __DbViewBase["myConversationMessages"];
  readonly "my_conversations": __DbViewBase["myConversations"];
  readonly "flat_rule": __DbViewBase["flatRule"];
  readonly "pantry_item": __DbViewBase["pantryItem"];
  readonly "shared_memory": __DbViewBase["sharedMemory"];
  readonly "expense_split": __DbViewBase["expenseSplit"];
};

type __TablesBase = __QueryBuilder<typeof tablesSchema.schemaType>;
export type Tables = __TablesBase & {
  readonly "my_ai_status": __TablesBase["myAiStatus"];
  readonly "my_conversation_messages": __TablesBase["myConversationMessages"];
  readonly "my_conversations": __TablesBase["myConversations"];
  readonly "flat_rule": __TablesBase["flatRule"];
  readonly "pantry_item": __TablesBase["pantryItem"];
  readonly "shared_memory": __TablesBase["sharedMemory"];
  readonly "expense_split": __TablesBase["expenseSplit"];
};

/** The tables available in this remote SpacetimeDB module. */
const tablesBase: __TablesBase = __makeQueryBuilder(tablesSchema.schemaType);
export const tables: Tables = __withTableAccessorAliases(tablesBase, true) as Tables;

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

export type EventContext = Omit<__EventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
export type ReducerEventContext = Omit<__ReducerEventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
export type SubscriptionEventContext = Omit<__SubscriptionEventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
export type ErrorContext = Omit<__ErrorContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  declare db: DbView;

  constructor(config: __DbConnectionConfig<typeof REMOTE_MODULE>) {
    super(config);
    this.db = __withTableAccessorAliases(this.db) as DbView;
  }

  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}
