// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  billReviewId: __t.u64().name("bill_review_id"),
  flatId: __t.u64().name("flat_id"),
  lineKey: __t.string().name("line_key"),
  label: __t.string(),
  amountPaise: __t.i64().name("amount_paise"),
  position: __t.u32(),
});
