// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  flatId: __t.u64().primaryKey().name("flat_id"),
  quietHoursStart: __t.string().name("quiet_hours_start"),
  quietHoursEnd: __t.string().name("quiet_hours_end"),
  defaultBillingSplit: __t.string().name("default_billing_split"),
  invitesEnabled: __t.bool().name("invites_enabled"),
  updatedBy: __t.identity().name("updated_by"),
  updatedAt: __t.timestamp().name("updated_at"),
});
