// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  identity: __t.identity(),
  flatId: __t.u64().name("flat_id"),
  displayName: __t.string().name("display_name"),
  role: __t.string(),
  active: __t.bool(),
  joinedAt: __t.timestamp().name("joined_at"),
});
