// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  pantryItemId: __t.u64().primaryKey().name("pantry_item_id"),
  flatId: __t.u64().name("flat_id"),
  category: __t.string(),
  location: __t.string(),
  lowStockThreshold: __t.i32().name("low_stock_threshold"),
  useSoon: __t.bool().name("use_soon"),
  updatedAt: __t.timestamp().name("updated_at"),
});
