// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  sessionId: __t.string().primaryKey().name("session_id"),
  owner: __t.identity(),
  flatId: __t.u64().name("flat_id"),
  phase: __t.string(),
  addressId: __t.string().name("address_id"),
  requestedItemsJson: __t.string().name("requested_items_json"),
  selectedItemsJson: __t.string().name("selected_items_json"),
  cartJson: __t.string().name("cart_json"),
  paymentJson: __t.string().name("payment_json"),
  toolContextJson: __t.string().name("tool_context_json"),
  pendingConfirmation: __t.bool().name("pending_confirmation"),
  updatedAt: __t.timestamp().name("updated_at"),
});
