// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  subjectIdentity: __t.identity().name("subject_identity"),
  subjectName: __t.string().name("subject_name"),
  category: __t.string(),
  memoryKey: __t.string().name("memory_key"),
  value: __t.string(),
  sourceMessageId: __t.u64().name("source_message_id"),
  updatedAt: __t.timestamp().name("updated_at"),
});
