// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AiConfig = __t.object("AiConfig", {
  owner: __t.identity(),
  apiKey: __t.string(),
  model: __t.string(),
  updatedAt: __t.timestamp(),
});
export type AiConfig = __Infer<typeof AiConfig>;

export const AiStatus = __t.object("AiStatus", {
  configured: __t.bool(),
  verified: __t.bool(),
  model: __t.string(),
});
export type AiStatus = __Infer<typeof AiStatus>;

export const AiVerification = __t.object("AiVerification", {
  owner: __t.identity(),
  verifiedAt: __t.timestamp(),
});
export type AiVerification = __Infer<typeof AiVerification>;

export const Conversation = __t.object("Conversation", {
  id: __t.string(),
  flatId: __t.u64(),
  owner: __t.identity(),
  title: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Conversation = __Infer<typeof Conversation>;

export const ConversationMessage = __t.object("ConversationMessage", {
  id: __t.u64(),
  conversationId: __t.string(),
  owner: __t.identity(),
  role: __t.string(),
  agent: __t.string(),
  content: __t.string(),
  createdAt: __t.timestamp(),
});
export type ConversationMessage = __Infer<typeof ConversationMessage>;

export const Expense = __t.object("Expense", {
  id: __t.u64(),
  flatId: __t.u64(),
  title: __t.string(),
  amountPaise: __t.i64(),
  paidBy: __t.identity(),
  category: __t.string(),
  breakdownJson: __t.string(),
});
export type Expense = __Infer<typeof Expense>;

export const ExpenseSplit = __t.object("ExpenseSplit", {
  id: __t.u64(),
  expenseId: __t.u64(),
  memberIdentity: __t.identity(),
  amountPaise: __t.i64(),
  settled: __t.bool(),
  reason: __t.string(),
});
export type ExpenseSplit = __Infer<typeof ExpenseSplit>;

export const Flat = __t.object("Flat", {
  id: __t.u64(),
  residenceId: __t.u64(),
  name: __t.string(),
  flatNumber: __t.string(),
  createdAt: __t.timestamp(),
});
export type Flat = __Infer<typeof Flat>;

export const FlatRule = __t.object("FlatRule", {
  id: __t.u64(),
  flatId: __t.u64(),
  ruleType: __t.string(),
  title: __t.string(),
  description: __t.string(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
});
export type FlatRule = __Infer<typeof FlatRule>;

export const Member = __t.object("Member", {
  identity: __t.identity(),
  flatId: __t.u64(),
  displayName: __t.string(),
});
export type Member = __Infer<typeof Member>;

export const MyAiStatus = __t.object("MyAiStatus", {});
export type MyAiStatus = __Infer<typeof MyAiStatus>;

export const MyConversationMessages = __t.object("MyConversationMessages", {});
export type MyConversationMessages = __Infer<typeof MyConversationMessages>;

export const MyConversations = __t.object("MyConversations", {});
export type MyConversations = __Infer<typeof MyConversations>;

export const PantryItem = __t.object("PantryItem", {
  id: __t.u64(),
  flatId: __t.u64(),
  name: __t.string(),
  quantity: __t.i32(),
  unit: __t.string(),
  updatedBy: __t.identity(),
});
export type PantryItem = __Infer<typeof PantryItem>;

export const Residence = __t.object("Residence", {
  id: __t.u64(),
  name: __t.string(),
  address: __t.string(),
  createdAt: __t.timestamp(),
});
export type Residence = __Infer<typeof Residence>;

export const SharedMemory = __t.object("SharedMemory", {
  id: __t.u64(),
  flatId: __t.u64(),
  subjectIdentity: __t.identity(),
  subjectName: __t.string(),
  category: __t.string(),
  memoryKey: __t.string(),
  value: __t.string(),
  sourceMessageId: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type SharedMemory = __Infer<typeof SharedMemory>;

