// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  sessionId: __t.string(),
  phase: __t.string(),
  addressId: __t.string(),
  requestedItemsJson: __t.string(),
  selectedItemsJson: __t.string(),
  cartJson: __t.string(),
  paymentJson: __t.string(),
  toolContextJson: __t.string(),
  pendingConfirmation: __t.bool(),
};
