// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddChatMessageReducer from "../add_chat_message_reducer";
import AddPantryItemReducer from "../add_pantry_item_reducer";
import RecordExpenseReducer from "../record_expense_reducer";
import SetDisplayNameReducer from "../set_display_name_reducer";

export type AddChatMessageParams = __Infer<typeof AddChatMessageReducer>;
export type AddPantryItemParams = __Infer<typeof AddPantryItemReducer>;
export type RecordExpenseParams = __Infer<typeof RecordExpenseReducer>;
export type SetDisplayNameParams = __Infer<typeof SetDisplayNameReducer>;

