// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddPantryItemReducer from "../add_pantry_item_reducer";
import AppendConversationMessageReducer from "../append_conversation_message_reducer";
import ClearAllDataReducer from "../clear_all_data_reducer";
import CompleteReminderReducer from "../complete_reminder_reducer";
import CreateAndJoinFlatReducer from "../create_and_join_flat_reducer";
import CreateBillReviewReducer from "../create_bill_review_reducer";
import CreateConversationReducer from "../create_conversation_reducer";
import CreateHomeAndJoinReducer from "../create_home_and_join_reducer";
import CreateHomeInvitationReducer from "../create_home_invitation_reducer";
import CreateReminderReducer from "../create_reminder_reducer";
import CreateResidenceReducer from "../create_residence_reducer";
import DeleteBillLineReducer from "../delete_bill_line_reducer";
import DeleteBillLineAllocationReducer from "../delete_bill_line_allocation_reducer";
import DeleteFlatRuleReducer from "../delete_flat_rule_reducer";
import DeleteMyAccountReducer from "../delete_my_account_reducer";
import DeletePantryItemReducer from "../delete_pantry_item_reducer";
import JoinFlatReducer from "../join_flat_reducer";
import JoinHomeWithInviteReducer from "../join_home_with_invite_reducer";
import RecordExpenseReducer from "../record_expense_reducer";
import RecordReviewedBillReducer from "../record_reviewed_bill_reducer";
import RevokeHomeInvitationReducer from "../revoke_home_invitation_reducer";
import SetAiConfigReducer from "../set_ai_config_reducer";
import SetDisplayNameReducer from "../set_display_name_reducer";
import SwitchHomeReducer from "../switch_home_reducer";
import UpdateResidenceFlatReducer from "../update_residence_flat_reducer";
import UpsertBillAllocationReducer from "../upsert_bill_allocation_reducer";
import UpsertBillLineReducer from "../upsert_bill_line_reducer";
import UpsertBillLineAllocationReducer from "../upsert_bill_line_allocation_reducer";
import UpsertFlatRuleReducer from "../upsert_flat_rule_reducer";
import UpsertHomeSettingsReducer from "../upsert_home_settings_reducer";
import UpsertPantryItemReducer from "../upsert_pantry_item_reducer";
import UpsertSharedMemoryReducer from "../upsert_shared_memory_reducer";

export type AddPantryItemParams = __Infer<typeof AddPantryItemReducer>;
export type AppendConversationMessageParams = __Infer<typeof AppendConversationMessageReducer>;
export type ClearAllDataParams = __Infer<typeof ClearAllDataReducer>;
export type CompleteReminderParams = __Infer<typeof CompleteReminderReducer>;
export type CreateAndJoinFlatParams = __Infer<typeof CreateAndJoinFlatReducer>;
export type CreateBillReviewParams = __Infer<typeof CreateBillReviewReducer>;
export type CreateConversationParams = __Infer<typeof CreateConversationReducer>;
export type CreateHomeAndJoinParams = __Infer<typeof CreateHomeAndJoinReducer>;
export type CreateHomeInvitationParams = __Infer<typeof CreateHomeInvitationReducer>;
export type CreateReminderParams = __Infer<typeof CreateReminderReducer>;
export type CreateResidenceParams = __Infer<typeof CreateResidenceReducer>;
export type DeleteBillLineParams = __Infer<typeof DeleteBillLineReducer>;
export type DeleteBillLineAllocationParams = __Infer<typeof DeleteBillLineAllocationReducer>;
export type DeleteFlatRuleParams = __Infer<typeof DeleteFlatRuleReducer>;
export type DeleteMyAccountParams = __Infer<typeof DeleteMyAccountReducer>;
export type DeletePantryItemParams = __Infer<typeof DeletePantryItemReducer>;
export type JoinFlatParams = __Infer<typeof JoinFlatReducer>;
export type JoinHomeWithInviteParams = __Infer<typeof JoinHomeWithInviteReducer>;
export type RecordExpenseParams = __Infer<typeof RecordExpenseReducer>;
export type RecordReviewedBillParams = __Infer<typeof RecordReviewedBillReducer>;
export type RevokeHomeInvitationParams = __Infer<typeof RevokeHomeInvitationReducer>;
export type SetAiConfigParams = __Infer<typeof SetAiConfigReducer>;
export type SetDisplayNameParams = __Infer<typeof SetDisplayNameReducer>;
export type SwitchHomeParams = __Infer<typeof SwitchHomeReducer>;
export type UpdateResidenceFlatParams = __Infer<typeof UpdateResidenceFlatReducer>;
export type UpsertBillAllocationParams = __Infer<typeof UpsertBillAllocationReducer>;
export type UpsertBillLineParams = __Infer<typeof UpsertBillLineReducer>;
export type UpsertBillLineAllocationParams = __Infer<typeof UpsertBillLineAllocationReducer>;
export type UpsertFlatRuleParams = __Infer<typeof UpsertFlatRuleReducer>;
export type UpsertHomeSettingsParams = __Infer<typeof UpsertHomeSettingsReducer>;
export type UpsertPantryItemParams = __Infer<typeof UpsertPantryItemReducer>;
export type UpsertSharedMemoryParams = __Infer<typeof UpsertSharedMemoryReducer>;

