// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddChatMessageReducer from "../add_chat_message_reducer";
import AddPantryItemReducer from "../add_pantry_item_reducer";
import AppendConversationMessageReducer from "../append_conversation_message_reducer";
import CreateConversationReducer from "../create_conversation_reducer";
import RecordExpenseReducer from "../record_expense_reducer";
import ReplaceShoppingItemsReducer from "../replace_shopping_items_reducer";
import SetAiConfigReducer from "../set_ai_config_reducer";
import SetDisplayNameReducer from "../set_display_name_reducer";
import UpsertSharedMemoryReducer from "../upsert_shared_memory_reducer";

export type AddChatMessageParams = __Infer<typeof AddChatMessageReducer>;
export type AddPantryItemParams = __Infer<typeof AddPantryItemReducer>;
export type AppendConversationMessageParams = __Infer<typeof AppendConversationMessageReducer>;
export type CreateConversationParams = __Infer<typeof CreateConversationReducer>;
export type RecordExpenseParams = __Infer<typeof RecordExpenseReducer>;
export type ReplaceShoppingItemsParams = __Infer<typeof ReplaceShoppingItemsReducer>;
export type SetAiConfigParams = __Infer<typeof SetAiConfigReducer>;
export type SetDisplayNameParams = __Infer<typeof SetDisplayNameReducer>;
export type UpsertSharedMemoryParams = __Infer<typeof UpsertSharedMemoryReducer>;

